config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  resources :portifolios, except: [:show]
  get 'portifolio/:id', to: 'portifolios#show', as: 'portifolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: {message: 'Campo obrigatório!!!'}
  validates :body,  presence: true

  scope :orderDescendent, -> { all.order('created_at DESC') }
end

app/models/portifolio.rb
class Portifolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_find, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.orderDescendent
  end

  def show
    @blog = Blog.friendly.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog, notice: 'Created with success!!!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Update with success'
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to root_url
  end

  private
    def set_find
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  helper_method :status

  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end

  # private
    def status(a, b)
      a + b
    end
end

app/controllers/portifolios_controller.rb
class PortifoliosController < ApplicationController

  before_action :set_find, only: [:show, :edit, :update, :destroy]

  def index
    @portifolio_items = Portifolio.all
  end

  def show
  end

  def new
    @portifolio_item = Portifolio.new
  end

  def create
    @portifolio_item = Portifolio.new(portifolio_params)
    if @portifolio_item.save
      redirect_to @portifolio_item, notice: 'Created with success'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @portifolio_item.update(portifolio_params)
      redirect_to @portifolio_item, notice: 'Updated with success!'
    else
      render 'edit'
    end
  end

  def destroy
    @portifolio_item.destroy
    redirect_to portifolios_path
  end

  private
    def portifolio_params
      params.require(:portifolio).permit(:title, :subtitle, :body)
    end

    def set_find
      @portifolio_item = Portifolio.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portifolios_helper.rb
module PortifoliosHelper
end

app/views/blogs/_form.html.haml
= form_with(model: @blog, local: true) do |f|
  .field
    = f.label :title, class: 'label'
    .control
      = f.text_field :title, class: 'input', autofocus: true, placeholder: 'Your title here...'

  .field
    = f.label :body, class: 'label'
    .control
      = f.text_area :body, class: 'textarea'

  .field
    .control
      = f.button :submit, class: 'button is-primary'

  = link_to 'Back', :back

app/views/blogs/edit.html.haml
%section.section
  .container
    %h2.subtitle.is-4 Edit
    = render 'form'

    -# = link_to 'Cancel', root_url, class: 'link'

app/views/blogs/index.html.haml
%section.section
  .container
    .column.is-half
      %h1.title.is-3 My Blog

      %br

      - @blogs.each do |blog|
        = link_to blog_path(blog), class: 'link' do
          %h2.subtitle.is-4= blog.title
        .tags.has-addons
          %span.tag.is-primary
            = link_to 'edit', edit_blog_path(blog), class: 'has-text-white'
          %span.tag.is-danger
            = link_to 'delete', blog_path(blog), method: :delete, class: 'has-text-white' 
        %p= truncate(blog.body, length: 50)
        %br

      = link_to 'New Article', new_blog_path, class: 'link'

app/views/blogs/new.html.haml
%section.section
  .container
    %h1.title New Article
    = render 'form'

app/views/blogs/show.html.haml
%section.section
  .container
    %h1.title.is-4= @blog.title
    %p
      = @blog.body
    %br
    = link_to 'Editar', edit_blog_path(@blog), class: 'button is-primary'
    %br
    = link_to 'Back', :back

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Base Config
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', { :media => 'all', :data => {:turbolinks => {:track => 'reload'}} }
    = javascript_pack_tag 'application', { :data => {:turbolinks => {:track => 'reload'}}}

  %body
  
    = yield

app/views/pages/about.html.haml
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.haml
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.haml
%section.section
  %h1.title.has-text-red Página home

  = @posts.inspect
  %hr
  = @skills.inspect

app/views/portifolios/_form.html.haml
= form_with model: @portifolio_item, local:true do |form|
  .field
    = form.label :title, class: 'label'
    .control
      = form.text_field :title, class: 'input', placeholder: 'your title', autofocus: true
  .field
    = form.label :subtitle, class: 'label'
    .control
      = form.text_area :body, class: 'textarea', placeholder: 'add your portifolio text'
  .field
    .actions
      = form.button :submit, class: 'button is-primary'

app/views/portifolios/edit.html.haml
%h1.title Edit Portifolio Item

= render 'form'

app/views/portifolios/index.html.haml
%h2.title.is-2 Welcome my portifolio
= link_to 'New Portifólio', new_portifolio_path
%hr
- @portifolio_items.each do |portifolio|
  %h1.title.is-5= link_to portifolio.title, portifolio_show_path(portifolio)
  %h2.subtitle.is-6= portifolio.subtitle
  %p= portifolio.body
  %figure.image
    = image_tag(portifolio.thumb_image, {style:'width: 250px'}) unless portifolio.thumb_image.nil?
  %br
  = link_to 'Edit', edit_portifolio_path(portifolio)
  |
  = link_to 'Delete Portifolio Item', portifolio_path(portifolio), method: :delete, data:{ confirm: 'You are sure?' }
  %br
  %br

app/views/portifolios/new.html.haml
%h1.title Create a new Portifolio Item

= render 'form'

app/views/portifolios/show.html.haml
%figure.image
= image_tag(@portifolio_item.main_image)
%h1.title= @portifolio_item.title
%br
%em= @portifolio_item.subtitle
%p= @portifolio_item.body